window.alert('Site de Titulos de Times Mineiros')
var time = window.prompt('Dentre os times, 1 - Cruzeiro, 2 - Atletico e 3 - America escolha o numero referente a um deles.')

function carregar(){
    var nt = window.document.getElementById('nometime')
    var imgt = window.document.getElementById('img')
    var tit = window.document.getElementById('titulo')
    if (time != 1 && time != 2 && time != 3 ) {
        window.alert('Valor incorreto. Atualize a pagina e digite novamente!')
    } else {
    
        if (time =='1'){
            nt.innerHTML = 'Cruzeiro Esporte Clube'
            imgt.src = 'image/cruzeiro.png'
            imgt.style.height= '300px'
            imgt.style.width = '300px'
            tit.innerHTML  = 'No Futebol o Cruzeiro tem 20 Títulos oficiais nos níveis internacional, nacional e regional. Em nível internacional o Cruzeiro conquistou por duas vezes a Copa Libertadores da América (1976 / 1997) tornando-se bicampeão, conquistou por duas vezes a Supercopa Libertadores (1991 / 1992) tornando-se bicampeão, conquistou a por uma vez a Copa de Ouro Nicolás Leoz (1995), conquistou a por uma vez a Copa Master da Supercopa (1995) e conquistou por uma vez a Recopa Sul-Americana (1998) sendo ao todo 7 Títulos internacionais oficiais reconhecidos pela CONMEBOL.<br>Em nível nacional o Cruzeiro conquistou por quatro vezes o Campeonato Brasileiro de Futebol (1966 / 2003 / 2013 e 2014) tornando-se tetracampeão, sendo o único campeão fora do eixo RJ-SP na era dos pontos corridos. Conquistou por seis vezes a Copa do Brasil de Futebol (1993 / 1996 / 2000 / 2003 / 2017 e 2018) tornando-se hexacampeão, e em 2018 o primeiro a conquistar a taça por dois anos consecutivos. Com a conquista do hexa o Cruzeiro torna-se o maior campeão da historia da Copa do Brasil. Na soma total de títulos nacionais o Cruzeiro tem 10 Títulos oficiais reconhecidos pela CBF.<br>No que diz respeito ao somatório de títulos oficiais de abrangência nacional e internacional de clubes brasileiros de futebol (sem contar títulos oficiais de abrangência estadual e regional), em setembro de 2019 o Cruzeiro figurava como segundo colocado, empatado com o Santos FC e SE Palmeiras e ultrapassado somente pelo São Paulo FC, sendo então a única agremiação não-paulista a figurar com mais títulos desta abrangência que um dos quatro grandes clubes paulistas, no caso o SC Corinthians P.<br>Em nível regional e estadual o Cruzeiro conquistou por duas vezes a Copa Sul-Minas (2001 e 2002) tornando-se bicampeão, conquistou por uma vez a Copa Centro-Oeste (1999) sendo ao todo 3 títulos oficiais reconhecidos. Em nível estadual, o Cruzeiro conquistou por 38 vezes o Campeonato Mineiro sendo um dos maiores campeões.'
            document.body.style.background = 'rgb(9,30,85)'

        } else if (time == 2) {
            nt.innerHTML = 'Clube Atletico Mineiro'
            imgt.src = 'image/atletico.png'
            imgt.style.height= '300px'
            imgt.style.width = '300px'
            tit.innerHTML  = '<p>O Clube Atlético Mineiro (conhecido apenas por Atlético e cujo acrônimo é CAM) é um clube brasileiro de futebol sediado na cidade de Belo Horizonte, Minas Gerais. Foi fundado em 25 de março de 1908 por um grupo de estudantes, tem como suas cores tradicionais o preto e o branco. O clube teve como primeiro nome Athlético Mineiro Football Club, adotando, em 1913, seu nome definitivo.Seu símbolo e alcunha mais popular é o Galo, mascote oficial no final da década de 1930. <br>Embora tenha atuado em outras modalidades esportivas ao longo dos anos, seu reconhecimento e suas principais conquistas foram alcançados no futebol. O clube é o maior campeão do Campeonato Mineiro com 47 troféus, além de ser o maior vencedor do Clássico Mineiro, com uma grande vantagem contra seu rival, o Cruzeiro. No âmbito nacional, foi campeão brasileiro duas vezes, em 1971 e 2021, além de outros cinco títulos nacionais oficiais: a Copa dos Campeões (FBF) em 1937,[14][15] a Copa dos Campeões (CBD) em 1978,, a Copa do Brasil, em 2014 e 2021 e a Supercopa do Brasil de 2022 . Na esfera internacional, possui quatro títulos oficiais:uma Copa Libertadores da América, duas Copas Conmebol e uma Recopa Sul-Americana.<br>Em 2014 o Atlético foi eleito o melhor time da América do Sul, e o 6º melhor do mundo, conforme o ranking elaborado pela IFFHS. No ano de 2017 o Atlético novamente apareceu no ranking da IFFHS, agora como melhor time da América do Sul e 13º do mundo. Em 2021, a IFFHS elaborou o ranking de clubes da América do Sul, com dados estatísticos de 2011 a 2020, no qual o Atlético se destacou como o 9º melhor clube da América do Sul na década. Em 2022, a IFFHS publicou novo ranking referente ao ano anterior e o Atlético foi eleito o 2° melhor clube do mundo na temporada 2021. Um outro grande feito do Atlético é o de ser, junto ao Dublin-URU, Santa Cruz, Arsenal-ING, e do Flamengo, um dos 5 únicos clubes do mundo que já venceram a Seleção Brasileira de Futebol.<br>'
            tit.innerHTML  += 'De modalidades esportivas importantes ao longo da história atleticana, destacam-se o voleibol, onde o clube é ainda hoje o segundo maior campeão estadual (apenas atrás do Minas Tênis Clube). O atletismo rendeu ao clube três conquistas na Corrida Internacional de São Silvestre, conquistados por João da Mata (1983) e Robert Cheruiyot (2007) no masculino, e Alice Timbilili (2007) no feminino. No futsal, o Atlético Pax de Minas, através de craques como Manoel Tobias e Falcão, dominou o Brasil e o mundo, conquistando títulos como a Taça Brasil em 1985, a Liga Futsal em 1997 e 1999, e a Copa Intercontinental em 1998.</P>'
            document.body.style.background = 'black;'

            }else {
                nt.innerHTML = 'América Futebol Clube'
                imgt.src = 'image/america.png'
                imgt.style.height= '300px'
                imgt.style.width = '300px'
                tit.innerHTML  = 'O América Futebol Clube, também conhecido como América, América Mineiro ou Coelho, é um clube desportivo brasileiro da cidade de Belo Horizonte, capital do estado brasileiro de Minas Gerais.<br>Fundado em 30 de abril de 1912, o clube preserva o mesmo nome e escudo desde sua criação. Suas cores de jogo são o verde, o branco (desde 1912) e o preto, que foi incorporado ao uniforme, em 1913, um ano após a fundação. Hoje, as três cores fazem parte das variações dos uniformes do tricolor América, mas o time também atuou com uniformes vermelhos entre 1933 e 1942, em protesto à introdução do profissionalismo no futebol.<br>O clube é proprietário do Estádio Independência, sendo o único de Belo Horizonte a mandar seus jogos em estádio próprio, com o América possuindo a terceira maior torcida entre clubes de Minas Gerais e já tendo disputado mais de 4.300 partidas em sua História. Seu maior rival é o Atlético, com quem realiza o Clássico das Multidões, possuindo uma forte rivalidade com o também belo-horizontino Cruzeiro, tendo ainda como um de seus oponentes o também tradicional Villa Nova, de Nova Lima.<br>O América é um dos clubes mais tradicionais e bem sucedidos do Estado: recordista de participações no Campeonato Mineiro de Futebol,[carece de fontes] conquistou 16 títulos estaduais e foi vice-campeão em outras 16 oportunidades em um total de 68 vezes no G-4. As 10 primeiras conquistas foram em sequência entre 1916 a 1925, um recorde nacional de títulos consecutivos, façanha essa compartilhada com o ABC (RN), com a conquista mais recente tendo sido em 2016. Dentre os demais títulos, destacam-se as conquistas nacionais da Série B em 1997 e 2017, da Série C em 2009 e da Copa Sul-Minas de 2000, com a melhor campanha na Série A do Campeonato Brasileiro tendo ocorrido na edição de 1973, quando o Coelho obteve a sétima colocação entre 40 participantes, e na Copa do Brasil o terceiro lugar na edição de 2020.<br>'
                tit.innerHTML  += 'O clube é reconhecido por sua tradição na formação de novos jogadores. Entre as suas principais revelações, destacam-se Tostão, Éder, Palhinha, Gilberto Silva, Euller, Nakazawa, Alex Mineiro, Fred, Danilo e Richarlison. O América possui os 3 principais títulos nacionais das categorias de base: Copa São Paulo de Juniores de 1996, Campeonato Brasileiro de Futebol Sub-20 de 2011, e duas Taça Belo Horizonte de Futebol Júnior, em 2000 e em 2014.<br>No dia 09 de dezembro de 2021, assegurou a classificação histórica para a fase prévia da Copa Libertadores da América de 2022, sendo esta a primeira participação do América na Copa Libertadores da América em 109 anos.'
                document.body.style.background = 'rgb(0,127,78)'
            }
        } 
    }

        